main:
#	g++ -o main main.c -I/home/zjq/deep_learning/anaconda3/include/ -lpython3.6m
	g++ -o main main.c -I/home/zjq/deep_learning/anaconda3/include/ -L/home/zjq/deep_learning/anaconda3/lib -lpython3.6m
clean:
	rm main *.o -rf
